### ISSUE TITLE
support for custom user data

### ISSUE THREAD

**Issue by etsrepo** [stormpath/stormpath-passport-express-sample#12]
support for custom user data

**Comment by rdegges** [comment]
You can use customdata currently -- the way you do it is via the user object in your route code.

So for instance, if you're inside a route, you might write some code like this:

```javascript
req.user.getCustomData(function(err, data) {
  if (err) {
    res.send(503);
  } else {
    res.send(data); // data is the user's custom data as JSON
  }
});
```

**Comment by etsrepo** [comment]
sorry, Its was my mistake.. your code is running very smooth 

thanks for this sample

**Comment by rdegges** [comment]
happy to help!
