### ISSUE TITLE
rolling sessions

### ISSUE THREAD

**Issue by braindevils** [stormpath/stormpath-passport-express-sample#14]
Hi,

How can I implement rolling sessions using express-stormpath? (cookies get touched on every request, sessions expire only after an amount of inactivity)

Marijn

**Comment by robertjd** [comment]
Hi Marjin,

This package is using the Express session library, which appears to have the options you are looking for.  Have you tried configuring it with this library?  Here it is:

https://github.com/expressjs/session

**Comment by braindevils** [comment]
Hi RObert,

I have tried that, but it didn’t work for me. Cookies are not updated on subsequent requests. Any more clues?

Thanks,

Marijn

**Comment by rdegges** [comment]
Hey Marijn,

One thing you might wanna try is directly adding a random number to the session via some custom middleware. EG: here's some pseudocode:

```javascript
var uuid = require('node-uuid');

app.use(function(req, res, next) {
  req.session.random = uuid.v4();
  next();
});
```

This would guarantee the session is 'touched' on every request, as you'll be explicitly modifying a session value.

**Comment by braindevils** [comment]
Obviously that works. Thanks!
