### ISSUE TITLE
apiKey Required Error

### ISSUE THREAD

**Issue by RPSource** [stormpath/stormpath-passport-express-sample#15]
I know this question has been asked before but all the solutions don't seem to work for me:

I keep getting the "apiKey.id is required." error and the app can't start.

I created a .env file with the correct data and did a
```
source .env
```
command

but whatever I do. the error keeps returning.
I am running on OSX 10.10.3

**Comment by RPSource** [comment]
I found the problem, the permissions on the .env file were not correct so the command would not register the env variables.

Problem is solved.

**Comment by rdegges** [comment]
Awesome! Glad it's working. <33
