### ISSUE TITLE
Api key issue while start application

### ISSUE THREAD

**Issue by gowthaman-murugan** [stormpath/stormpath-passport-express-sample#4]
$node App.js
/Stormpath/stormpath-express-sample/node_modules/passport-stormpath/node_modules/stormpath/lib/authc/RequestAuthenticator.js:8
    throw new Error('apiKey.id is required.');
          ^
Error: apiKey.id is required.
    at BasicRequestAuthenticator.RequestAuthenticator (/home/gowthaman/sample/Stormpath/stormpath-express-sample/node_modules/passport-stormpath/node_modules/stormpath/lib/authc/RequestAuthenticator.js:8:11)

**Comment by sgnl** [comment]
I have an issue where the .env file is not being created after running `npm install` and entering in my credentials.

error says: `source: no such file or directory: .env`

**Comment by robertjd** [comment]
As a quick fix you can manually create the `.env` file, and put this in it:

```bash
export STORMPATH_API_KEY_ID=your_api_key_id
export STORMPATH_API_KEY_SECRET=your_api_key_secret
export STORMPATH_APP_HREF=your_app_href
export EXPRESS_SECRET=your_express_secret
```

Then just run `source .env` before you start your project.  Hope this helps!

**Comment by sgnl** [comment]
That does help me right now, Thanks!

**Comment by ansuyaa** [comment]
I set the .env variables as well have the variables defined in stormpath.init in my server.js file. 
However, I still get the above error whenever I run node server.js. How do I fix it?
